### ISSUE TITLE
Separate out tests/expected results from code

### ISSUE THREAD

**Issue by fugkco** [cooklang/CookInSwift#2]
It would be nice to separate out the test cases and the expected results for them into a separate file that's parseable outside of Swift. Something like YAML or JSON format. This allows others to implement this in other languages and rely on the same the cases to validate their implementation.

**Comment by dubadub** [comment]
@umgefahren I started extracting test-cases into YAML format https://github.com/cooklang/CookInSwift/pull/10/files#diff-108cc582ddc8fb36abf94aa6a115396b00fe3465cfad02ba7a269e005f3a1429. I'm curious if that what you meant?

**Comment by dubadub** [comment]
Extracted tests, closing the issue.
