### ISSUE TITLE
Mentioning another implemntation

### ISSUE THREAD

**Issue by umgefahren** [cooklang/CookInSwift#3]
I wrote a CookLang Parser in Rust. Could you consider mentioning it?
My Project: https://github.com/umgefahren/cook-with-rust

**Comment by dubadub** [comment]
@umgefahren Great idea about meta. I think most of the discussion goes in spec repo. I setup [Discussions](https://github.com/cooklang/spec/discussions) there as well for more like a free style conversations. I'm thinking about renaming the `spec` repo into `meta` as you suggested.

**Comment by dubadub** [comment]
Closing the issue as now we have section in spec and on the web-site with implementations.
