### ISSUE TITLE
Ingredient at the end of file is not parsed properly.

### ISSUE THREAD

**Issue by ideruga** [cooklang/CookInSwift#8]
When the .cook file ends with this line:
```
abcde

Third step: add @Chicken soup{}
```

The output of the read CLI command is:

```
Ingredients:
    Chicken                       1

Steps:
     1. abcde
        [–]
     2. Third step: add Chicken soup
        [Chicken: 1]
```

Problem: instead of `[Chicken soup: 1]`, it only prints `[Chicken: 1]`

Also, try mentioning the ingredient quantity: `@Chicken soup{25%kg}`, in this case the read instruction outputs `[Chicken soup: 1]` (the quantity is wrong). 
Note: if you remove all the other lines, it works fine. The problem is probably linked to the empty line before the step...
Also: adding a dot in the end generates "illegal instruction".

**Comment by dubadub** [comment]
@ideruga thanks for reporting the issue. I'm trying to reproduce the issue but I'm unable to. Would you be able to share a file itself? I might be related to specific line ending symbols. Is it on Windows?

**Comment by dubadub** [comment]
Fixed. Changes are in CLI since `v0.0.13`.
